title: "Market Insights from ZSM Properties"
description: "Market insights and analysis from ZSM Properties"
url: "https://zsmseven.github.io"
baseurl: ""

theme: jekyll-text-theme
text_skin: dark

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

permalink: /post/:slug/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .DS_Store