service: zsmseven-tracker-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    POLYGON_API_KEY: ${env:POLYGON_API_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  getData:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /data
          method: get
          cors: true

plugins:
  - serverless-python-requirements