service: zsmseven-tracker-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    POLYGON_API_KEY: ${env:POLYGON_API_KEY}
    DYNAMODB_TABLE: ticker-data-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  fetchData:
    handler: lambda_function.lambda_handler
    events:
      - schedule:
          rate: cron(5,10,15,20,25,30,35,40,45,50 16 * * MON-FRI)
          enabled: true
resources:
  Resources:
    TickerDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: ticker
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: ticker
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements

# custom:
#   customDomain:
#     domainName: ${self:custom.domain.${self:provider.stage}}
#     basePath: ''
#     stage: ${self:provider.stage}
#     createRoute53Record: true

#   domain:
#     dev: devapi.zsmproperties.com
#     prod: api.zsmproperties.com