service: zsmseven-tracker-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  getData:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /data
          method: get
          cors: true

plugins:
  - serverless-python-requirements