name: Deploy Portfolio API

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'portfolio-api/**'
  workflow_dispatch:

jobs:
  deploy-portfolio-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          cd portfolio-api
          npm install

      - name: Build TypeScript
        run: |
          cd portfolio-api
          npm run build

      - name: Deploy Portfolio API
        run: |
          cd portfolio-api
          STAGE=${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          serverless deploy --stage $STAGE
        env:
          JWT_SECRET: ${{ github.ref == 'refs/heads/main' && secrets.PROD_JWT_SECRET || secrets.DEV_JWT_SECRET }}

      - name: Display deployment info
        run: |
          cd portfolio-api
          STAGE=${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          serverless info --stage $STAGE
          echo ""
          echo "Deployment complete!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Stage: $STAGE"
          echo "Domain: ${{ github.ref == 'refs/heads/main' && 'https://api.zsm7.com/portfolios' || 'https://api.zsmproperties.com/portfolios' }}"
