name: Deploy Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'templates/**'
      - 'static/**'
      - 'publish_pipeline.py'
      - 'test_links.py'
  workflow_dispatch:  # For manual testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:  # Add this block to grant write access
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask python-frontmatter markdown
    - name: Generate static site
      run: python publish_pipeline.py
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static_site
        cname: blog.zsmproperties.com