name: Deploy Options Trades API

on:
  push:
    branches:
      - main
    paths:
      - 'options-trades-api/**'
  workflow_dispatch:

jobs:
  deploy-options-trades-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          cd options-trades-api
          npm install

      - name: Build TypeScript
        run: |
          cd options-trades-api
          npm run build

      - name: Create custom domain (if needed)
        run: |
          cd options-trades-api
          serverless create_domain --stage prod || true
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Deploy Options Trades API
        run: |
          cd options-trades-api
          serverless deploy --stage prod
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Display deployment info
        run: |
          cd options-trades-api
          serverless info --stage prod
