name: Deploy Users API

on:
  push:
    branches:
      - main
    paths:
      - 'users-api/**'
  workflow_dispatch:

jobs:
  deploy-users-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          cd users-api
          npm install

      - name: Build TypeScript
        run: |
          cd users-api
          npm run build

      - name: Create custom domain mapping (if needed)
        run: |
          cd users-api
          echo "Creating domain mapping for /users base path..."
          serverless create_domain --stage prod || echo "✓ Domain mapping already exists"
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
        continue-on-error: true

      - name: Deploy Users API
        run: |
          cd users-api
          serverless deploy --stage prod
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

      - name: Display deployment info
        run: |
          cd users-api
          serverless info --stage prod
