name: Deploy Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'templates/**'
      - 'static/**'
      - 'publish_pipeline.py'
      - 'test_links.py'
      - 'www/**'
  workflow_dispatch:  # For manual testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask python-frontmatter markdown
    - name: Generate static site
      run: python publish_pipeline.py
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your preferred region
    - name: Deploy to S3
      run: |
        aws s3 sync ./static_site s3://blog.zsmproperties.com --delete --cache-control max-age=31536000,public
        aws s3 cp ./static_site/index.html s3://blog.zsmproperties.com/index.html --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html
    - name: Deploy www to S3
      run: |
        aws s3 sync ./www s3://www.zsmproperties.com --delete --cache-control max-age=31536000,public
        aws s3 cp ./www/index.html s3://www.zsmproperties.com/index.html --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html